### ISSUE TITLE
Crazy results when working with converted numbers

### ISSUE THREAD

**Issue by AlexDaniel** [samgwise/p6-Numeric-Pack#2]
```perl6
use Numeric::Pack :ALL;
my $buf = Buf[uint8].new(128,0,0,0);
say unpack-int32($buf) * 1; # -2147483648
say unpack-int32($buf) * ‘1’; # -18446744071562067968
```

I really don't know why this happens. Let me know if this is a rakodo bug (it does not happen with normal Ints, just the ones that come from Numeric::Pack).

**Comment by AlexDaniel** [comment]
Actually, that's a bug in rakudo. See [RT #131994](https://rt.perl.org/Ticket/Display.html?id=131994).

You may still want to add some tests for it, so I'll leave this ticket open.

**Comment by samgwise** [comment]
Thanks for pointing this out, I've just finished a substantial rewrite which is now covering a lot more edge cases (Like 8 byte uint64 unpacking!). All the return types should now be full perl 6 types, not natives so I'm going close this issue now. Let me know if you have anymore issues.

Also sorry for such a slow response.

**Comment by AlexDaniel** [comment]
Thank you, @samgwise!
